In [39]:
import glob
import os
import kagglehub
import pandas as pd

# 1. Descargar el dataset (reemplaza por el identificador correcto si cambia)
path = kagglehub.dataset_download("muhammaddawood42/nvidia-stock-data")

# 2. Buscar automáticamente el archivo CSV descargado
archivos_csv = glob.glob(os.path.join(path, "*.csv"))

if archivos_csv:
    archivo_target = archivos_csv[0]
    df = pd.read_csv(archivo_target)
    print(f"¡Cargado exitosamente desde: {archivo_target}!\n")
    display(df.head())
else:
    print("No se encontró ningún archivo CSV en la ruta descargada.")

¡Cargado exitosamente desde: C:\Users\Coder\.cache\kagglehub\datasets\muhammaddawood42\nvidia-stock-data\versions\1\NVIDIA_STOCK.csv!

,Price,Adj Close,Close,High,Low,Open,Volume
0,Ticker,NVDA,NVDA,NVDA,NVDA,NVDA,NVDA
1,Date,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-01-02,4.929879665374756,4.983749866485596,4.987500190734863,4.862500190734863,4.894499778747559,355616000
3,2018-01-03,5.254334926605225,5.3117499351501465,5.34250020980835,5.09375,5.102499961853027,914704000
4,2018-01-04,5.2820329666137695,5.339749813079834,5.451250076293945,5.317249774932861,5.394000053405762,583268000

In [40]:
# Eliminar las primeras 2 filas usando iloc (desde la fila 2 en adelante)
df = df.iloc[2:].reset_index(drop=True)

# Verificar el resultado
display(df.head())

,Price,Adj Close,Close,High,Low,Open,Volume
0,2018-01-02,4.929879665374756,4.983749866485596,4.987500190734863,4.862500190734863,4.894499778747559,355616000
1,2018-01-03,5.254334926605225,5.3117499351501465,5.34250020980835,5.09375,5.102499961853027,914704000
2,2018-01-04,5.2820329666137695,5.339749813079834,5.451250076293945,5.317249774932861,5.394000053405762,583268000
3,2018-01-05,5.326793670654297,5.385000228881836,5.422749996185303,5.2769999504089355,5.354750156402588,580124000
4,2018-01-08,5.490012168884277,5.550000190734863,5.625,5.4644999504089355,5.510000228881836,881216000

In [43]:
df.rename(columns={'Price': 'Date'}, inplace=True)

df['Date'] = pd.to_datetime(df['Date'])

columnas_a_convertir = ['Adj Close', 'Close', 'High', 'Low', 'Open']
df[columnas_a_convertir] = df[columnas_a_convertir].astype(float)

df['Volume'] = df['Volume'].astype(int)

display(df.head())
display(df.info())

        Date  Adj Close    Close     High      Low     Open     Volume
0 2018-01-02   4.929880  4.98375  4.98750  4.86250  4.89450  355616000
1 2018-01-03   5.254335  5.31175  5.34250  5.09375  5.10250  914704000
2 2018-01-04   5.282033  5.33975  5.45125  5.31725  5.39400  583268000
3 2018-01-05   5.326794  5.38500  5.42275  5.27700  5.35475  580124000
4 2018-01-08   5.490012  5.55000  5.62500  5.46450  5.51000  881216000

<class 'pandas.DataFrame'>
RangeIndex: 1697 entries, 0 to 1696
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1697 non-null   datetime64[us]
 1   Adj Close  1697 non-null   float64
 2   Close      1697 non-null   float64
 3   High       1697 non-null   float64
 4   Low        1697 non-null   float64
 5   Open       1697 non-null   float64
 6   Volume     1697 non-null   int64
dtypes: datetime64[us](1), float64(5), int64(1)
memory usage: 92.9 KB

None

In [44]:
from sqlalchemy import create_engine

# 1. Configura los datos de conexión a tu base de datos PostgreSQL
# Estructura: postgresql+psycopg2://usuario:contraseña@host:puerto/nombre_base_datos
usuario = "postgres"
password = "Jayzir18!"
host = "localhost"
port = "5432"
db_name = "Nvidia"

# 2. Crear el motor (engine) de conexión
engine = create_engine(f"postgresql+psycopg2://{usuario}:{password}@{host}:{port}/{db_name}")

# 3. Volcar todo el DataFrame a PostgreSQL
df.to_sql(
    name="acciones",  # Nombre que tendrá la tabla en la base de datos
    con=engine,                 # El motor de conexión que creamos
    if_exists="replace",        # Opciones: 'fail' (falla si existe), 'replace' (reemplaza la tabla), 'append' (agrega filas)
    index=False,                # True si quieres guardar el índice del DataFrame como una columna
    chunksize=10000             # Recomendado para datasets grandes: inserta en bloques de 10,000 filas
)

print("¡DataFrame exportado exitosamente a PostgreSQL!")

¡DataFrame exportado exitosamente a PostgreSQL!