In [2]:
import kagglehub
import os

path = kagglehub.dataset_download(
    "umichigan/world-religions"
)

print("Ruta:", path)

files = os.listdir(path)
print(f'\n"Archivos:", {files}')

c:\Users\Coder\Desktop\JayzirTech\RIWI\Data Analysis\env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Ruta: C:\Users\Coder\.cache\kagglehub\datasets\umichigan\world-religions\versions\1

"Archivos:", ['global.csv', 'national.csv', 'regional.csv']

In [3]:
import pandas as pd

df_global = pd.read_csv(os.path.join(path, "global.csv"))

df_regional = pd.read_csv(os.path.join(path, "regional.csv"))

df_national = pd.read_csv(os.path.join(path, "national.csv"))

In [5]:
df_global

,year,christianity_protestant,christianity_romancatholic,christianity_easternorthodox,christianity_anglican,christianity_other,christianity_all,judaism_orthodox,judaism_conservative,judaism_reform,...,baha’i_percent,taoism_percent,jainism_percent,confucianism_percent,syncretism_percent,animism_percent,noreligion_percent,otherreligion_percent,religion_sumpercent,total_percent
0,1945,160887585,391332035,98501171,36955033,13674466,701350290,856827,1426350,1929388,...,0.0000,0.0001,0.0000,0.0000,0.2666,0.0207,0.0955,0.0061,1.012061,0.718667
1,1950,133301043,401935856,106610911,38307544,16324768,696480122,2204231,1860297,2528641,...,0.0003,0.0004,0.0008,0.0012,0.1945,0.0400,0.0869,0.0055,1.011166,0.802432
2,1955,189347338,474378130,111661338,38177572,22437724,836002102,2496432,1653007,2225241,...,0.0003,0.0005,0.0006,0.0012,0.1521,0.0370,0.1199,0.0084,1.011792,0.834366
3,1960,220293770,541957872,118268109,41846700,44601144,966967595,2818847,1716903,2300405,...,0.0004,0.0005,0.0007,0.0012,0.1113,0.0465,0.1488,0.0065,1.013598,0.873137
4,1965,234437703,614115021,125954494,45086639,55119929,1074713786,3295632,1760345,2348076,...,0.0005,0.0005,0.0007,0.0014,0.1094,0.0491,0.1446,0.0126,1.006728,0.884908
5,1970,247932230,671006540,134595635,46079842,76991429,1176605676,3663721,1923986,2574798,...,0.0006,0.0005,0.0007,0.0014,0.1037,0.0457,0.1611,0.0072,1.012190,0.894433
6,1975,264857729,748325898,137192284,48153338,101587361,1300116609,3910099,2253657,2910930,...,0.0006,0.0007,0.0007,0.0013,0.0926,0.0419,0.1716,0.0067,1.012114,0.903261
7,1980,278962191,798834729,137902427,51093360,125285902,1392078609,4300992,2439116,3153787,...,0.0008,0.0009,0.0008,0.0013,0.0934,0.0388,0.1730,0.0082,0.977425,0.909855
8,1985,305061321,865316946,141435053,56651880,138453851,1506919051,4580474,2466942,3320124,...,0.0007,0.0010,0.0008,0.0003,0.0933,0.0356,0.1688,0.0078,0.976472,0.915925
9,1990,391772588,928527756,147970918,63954053,162855904,1695081219,4395315,1926083,2458253,...,0.0010,0.0011,0.0007,0.0002,0.0883,0.0343,0.1578,0.0068,1.009826,0.934234
10,1995,385509297,962614859,182860714,69080890,185349210,1785414969,5143346,1900415,2392642,...,0.0009,0.0012,0.0007,0.0002,0.0887,0.0340,0.1415,0.0074,1.008633,0.997009
11,2000,443610594,978633933,264356291,68291261,136031105,1890923184,5433428,1849587,2306902,...,0.0007,0.0016,0.0007,0.0006,0.0925,0.0274,0.1286,0.0055,1.009635,0.999342
12,2005,490942837,1013883916,255124896,69037503,161742315,1990731467,6271171,1778851,2342301,...,0.0007,0.0019,0.0007,0.0006,0.0885,0.0266,0.1156,0.0061,1.008920,0.995949
13,2010,557830085,1049709823,268783851,71770419,163818774,2111912953,6637406,1899567,2509660,...,0.0007,0.0014,0.0007,0.0006,0.0865,0.0255,0.1154,0.0039,1.008162,0.999792

In [7]:
df_regional.head()

# df_regional['region'].unique()

,year,region,christianity_protestant,christianity_romancatholic,christianity_easternorthodox,christianity_anglican,christianity_other,christianity_all,judaism_orthodox,judaism_conservative,...,taoism_percent,jainism_percent,confucianism_percent,syncretism_percent,animism_percent,noreligion_percent,otherreligion_percent,religion_sumpercent,total_percent,worldpopulation_percent
0,1945,Africa,2074180,672337,7251492,419457,4170594,14588060,0,0,...,0.0000,0.0,0.0,0.0000,0.3151,0.0003,0.0014,0.9997,1.0000,0.0180
1,1945,Asia,2407144,2222908,181928,3142204,1964907,9919091,0,0,...,0.0002,0.0,0.0,0.6378,0.0340,0.0462,0.0002,1.0043,1.0505,0.4103
2,1945,Europe,83145512,216041422,86503645,29855595,5361826,420908000,0,0,...,0.0000,0.0,0.0,0.0000,0.0023,0.1780,0.0045,0.8220,1.0000,0.3468
3,1945,Mideast,87174,635929,3180260,0,108332,4011695,0,0,...,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0073,1.0000,1.0000,0.0403
4,1945,West. Hem,73173575,171759439,1383846,3537777,2068807,251923444,856827,1426350,...,0.0000,0.0,0.0,0.0190,0.0008,0.0795,0.0230,0.9377,1.0172,0.1790

In [5]:
df_national.head()

# df_national['state'].unique()

,year,state,code,christianity_protestant,christianity_romancatholic,christianity_easternorthodox,christianity_anglican,christianity_other,christianity_all,judaism_orthodox,...,jainism_percent,confucianism_percent,syncretism_percent,animism_percent,noreligion_percent,otherreligion_percent,religion_sumpercent,total_percent,dual_religion,source_code
0,1945,United States of America,USA,66069671,38716742,1121898,2400000,1956807,110265118,821489,...,0.0,0.0,0.0,0.0,0.1635,0.0039,0.9961,1.0000,0,13
1,1950,United States of America,USA,73090083,42635882,3045420,3045420,1177214,122994019,1078078,...,0.0,0.0,0.0,0.0,0.1482,0.0041,0.9959,1.0000,0,18
2,1955,United States of America,USA,79294628,46402368,3454916,2572767,2277091,134001770,944000,...,0.0,0.0,0.0,0.0,0.1404,0.0193,0.9807,0.9999,0,15
3,1960,United States of America,USA,90692928,50587880,3334535,2710065,2908939,150234347,973500,...,0.0,0.0,0.0,0.0,0.1193,0.0076,0.9924,0.9999,0,13
4,1965,United States of America,USA,94165803,64761783,4792868,2822149,973155,167515758,991200,...,0.0,0.0,0.0,0.0,0.1020,0.0030,0.9970,1.0001,0,20

In [11]:
from sqlalchemy import create_engine

import os
from dotenv import load_dotenv

load_dotenv()

# 1. Configura los datos de conexión a tu base de datos PostgreSQL
# Estructura: postgresql+psycopg2://usuario:contraseña@host:puerto/nombre_base_datos
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")
db_name = os.getenv("DB_NAME")

# 2. Crear el motor (engine) de conexión
engine = create_engine(f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db_name}")

# 3. Diccionario con los DataFrames y los nombres que tendrán las tablas en PostgreSQL
tablas_a_exportar = {
    "global": df_global,
    "national": df_national,
    "regional": df_regional,
}

# 4. Iterar y enviar cada DataFrame a su respectiva tabla en Postgres
for table_name, df in tablas_a_exportar.items():
  try:
    df.to_sql(
        name=table_name,
        con=engine,
        if_exists="replace",  # Opciones: 'fail', 'replace' (reemplaza si existe), 'append' (agrega filas)
        index=False,  # Para que no guarde el índice numérico de Pandas como una columna extra
    )
    print(
        f"¡Éxito! DataFrame exportado correctamente a la tabla: {table_name} a {db_name.upper()}"
    )
  except Exception as e:
    print(f"Error al exportar {table_name}: {e}")

¡Éxito! DataFrame exportado correctamente a la tabla: global a WORLD_RELIGIONS
¡Éxito! DataFrame exportado correctamente a la tabla: national a WORLD_RELIGIONS
¡Éxito! DataFrame exportado correctamente a la tabla: regional a WORLD_RELIGIONS

In [7]:
print("Usuario:", user)
print("Host:", host)
print("Puerto:", port)
print("Base de datos:", db_name)
# (No imprimas la contraseña por seguridad, pero verifica que password no esté vacía)
print("¿Password cargada?:", bool(password))

Usuario: postgres
Host: localhost
Puerto: 5432
Base de datos: world_religions
¿Password cargada?: True

In [8]:
print("DB_NAME actual:", os.getenv("DB_NAME"))

DB_NAME actual: world_religions