In [77]:
import kagglehub
import os

path = kagglehub.dataset_download(
    "umichigan/world-religions"
)

print("Ruta:", path)

files = os.listdir(path)
print(f'\n"Archivos:", {files}')

Ruta: C:\Users\Coder\.cache\kagglehub\datasets\umichigan\world-religions\versions\1

"Archivos:", ['global.csv', 'national.csv', 'regional.csv']

In [86]:
import pandas as pd

df_global = pd.read_csv(os.path.join(path, "global.csv"))

df_regional = pd.read_csv(os.path.join(path, "regional.csv"))

df_global

df_regional

,year,region,christianity_protestant,christianity_romancatholic,christianity_easternorthodox,christianity_anglican,christianity_other,christianity_all,judaism_orthodox,judaism_conservative,...,taoism_percent,jainism_percent,confucianism_percent,syncretism_percent,animism_percent,noreligion_percent,otherreligion_percent,religion_sumpercent,total_percent,worldpopulation_percent
0,1945,Africa,2074180,672337,7251492,419457,4170594,14588060,0,0,...,0.0000,0.0000,0.0000,0.0000,0.3151,0.0003,0.0014,0.9997,1.0000,0.0180
1,1945,Asia,2407144,2222908,181928,3142204,1964907,9919091,0,0,...,0.0002,0.0000,0.0000,0.6378,0.0340,0.0462,0.0002,1.0043,1.0505,0.4103
2,1945,Europe,83145512,216041422,86503645,29855595,5361826,420908000,0,0,...,0.0000,0.0000,0.0000,0.0000,0.0023,0.1780,0.0045,0.8220,1.0000,0.3468
3,1945,Mideast,87174,635929,3180260,0,108332,4011695,0,0,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0073,1.0000,1.0000,0.0403
4,1945,West. Hem,73173575,171759439,1383846,3537777,2068807,251923444,856827,1426350,...,0.0000,0.0000,0.0000,0.0190,0.0008,0.0795,0.0230,0.9377,1.0172,0.1790
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,2010,Africa,143752568,165943467,38254839,38701490,73353476,460005841,0,0,...,0.0000,0.0001,0.0000,0.0001,0.0971,0.0111,0.0030,0.9889,1.0000,0.1169
66,2010,Asia,109770301,129766537,9690172,5059090,33635763,287921863,0,0,...,0.0026,0.0013,0.0010,0.1501,0.0210,0.1404,0.0019,0.8814,1.0217,0.5641
67,2010,Europe,65717165,244246870,201589183,19997856,26126910,557677984,0,0,...,0.0000,0.0000,0.0000,0.0007,0.0003,0.1735,0.0119,0.8265,1.0000,0.1103
68,2010,Mideast,2115645,5126980,10901720,16767,1652685,19813797,5517567,33439,...,0.0000,0.0000,0.0000,0.0000,0.0163,0.0074,0.0057,0.9926,1.0000,0.0718
69,2010,West. Hem,236474406,504625969,8347937,7995216,29049940,786493468,1119839,1866128,...,0.0000,0.0001,0.0001,0.0118,0.0078,0.1116,0.0053,0.8959,1.0075,0.1357

In [89]:
#print(df_global.columns)

df_global.head(1)

,year,christianity_protestant,christianity_romancatholic,christianity_easternorthodox,christianity_anglican,christianity_other,christianity_all,judaism_orthodox,judaism_conservative,judaism_reform,...,baha’i_percent,taoism_percent,jainism_percent,confucianism_percent,syncretism_percent,animism_percent,noreligion_percent,otherreligion_percent,religion_sumpercent,total_percent
0,1945,160887585,391332035,98501171,36955033,13674466,701350290,856827,1426350,1929388,...,0.0,0.0001,0.0,0.0,0.2666,0.0207,0.0955,0.0061,1.012061,0.718667

In [87]:
#print(df_regional.columns)

df_regional.head(7)

,year,region,christianity_protestant,christianity_romancatholic,christianity_easternorthodox,christianity_anglican,christianity_other,christianity_all,judaism_orthodox,judaism_conservative,...,taoism_percent,jainism_percent,confucianism_percent,syncretism_percent,animism_percent,noreligion_percent,otherreligion_percent,religion_sumpercent,total_percent,worldpopulation_percent
0,1945,Africa,2074180,672337,7251492,419457,4170594,14588060,0,0,...,0.0000,0.0000,0.000,0.0000,0.3151,0.0003,0.0014,0.9997,1.0000,0.0180
1,1945,Asia,2407144,2222908,181928,3142204,1964907,9919091,0,0,...,0.0002,0.0000,0.000,0.6378,0.0340,0.0462,0.0002,1.0043,1.0505,0.4103
2,1945,Europe,83145512,216041422,86503645,29855595,5361826,420908000,0,0,...,0.0000,0.0000,0.000,0.0000,0.0023,0.1780,0.0045,0.8220,1.0000,0.3468
3,1945,Mideast,87174,635929,3180260,0,108332,4011695,0,0,...,0.0000,0.0000,0.000,0.0000,0.0000,0.0000,0.0073,1.0000,1.0000,0.0403
4,1945,West. Hem,73173575,171759439,1383846,3537777,2068807,251923444,856827,1426350,...,0.0000,0.0000,0.000,0.0190,0.0008,0.0795,0.0230,0.9377,1.0172,0.1790
5,1950,Africa,3302860,736193,7260770,609769,4884121,16793713,0,0,...,0.0000,0.0000,0.000,0.0000,0.3288,0.0006,0.0001,0.9994,1.0000,0.0151
6,1950,Asia,9360004,25948053,1051829,3612715,5190796,45163397,0,0,...,0.0007,0.0014,0.002,0.3274,0.0585,0.0532,0.0004,0.9791,1.0324,0.5828

In [80]:
df_global = df_global.set_index('year')

df_christianity = df_global[['christianity_protestant', 'christianity_romancatholic', 'christianity_easternorthodox', 'christianity_anglican', 'christianity_other']]

df_judaism = df_global[['judaism_orthodox', 'judaism_conservative', 'judaism_reform', 'judaism_other']]

df_islam = df_global[['islam_sunni', 'islam_shi’a', 'islam_ibadhi', 'islam_nationofislam', 'islam_alawite', 'islam_ahmadiyya', 'islam_other']]

df_buddhism = df_global[['buddhism_mahayana', 'buddhism_theravada', 'buddhism_other']]

df_zoroastrianism = df_global[['zoroastrianism_all']]

df_hinduism = df_global[['hinduism_all']]

df_sikhism = df_global[['sikhism_all']]

df_shinto = df_global[['shinto_all']]

df_bahai = df_global[['baha’i_all']]

df_taoism = df_global[['taoism_all']]

df_jainism = df_global[['jainism_all']]

df_confucianism = df_global[['confucianism_all']]

df_syncretism = df_global[['syncretism_all']]

df_animism = df_global[['animism_all']]

df_noreligion = df_global[['noreligion_all']]

df_otherreligion = df_global[['otherreligion_all']]

In [81]:
'''from sqlalchemy import create_engine

import os
from dotenv import load_dotenv  

load_dotenv()

# 1. Configura los datos de conexión a tu base de datos PostgreSQL
# Estructura: postgresql+psycopg2://usuario:contraseña@host:puerto/nombre_base_datos
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")
db_name = os.getenv("DB_NAME")

# 2. Crear el motor (engine) de conexión
engine = create_engine(f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db_name}")

# 3. Volcar todo el DataFrame a PostgreSQL
dff.to_sql(
    name="dataset",  # Nombre que tendrá la tabla en la base de datos
    con=engine,                 # El motor de conexión que creamos
    if_exists="replace",        # Opciones: 'fail' (falla si existe), 'replace' (reemplaza la tabla), 'append' (agrega filas)
    index=False,                # True si quieres guardar el índice del DataFrame como una columna
    chunksize=10000             # Recomendado para datasets grandes: inserta en bloques de 10,000 filas
)

print("¡DataFrame exportado exitosamente a PostgreSQL!")'''

'from sqlalchemy import create_engine\n\nimport os\nfrom dotenv import load_dotenv  \n\nload_dotenv()\n\n# 1. Configura los datos de conexión a tu base de datos PostgreSQL\n# Estructura: postgresql+psycopg2://usuario:contraseña@host:puerto/nombre_base_datos\nuser = os.getenv("DB_USER")\npassword = os.getenv("DB_PASSWORD")\nhost = os.getenv("DB_HOST")\nport = os.getenv("DB_PORT")\ndb_name = os.getenv("DB_NAME")\n\n# 2. Crear el motor (engine) de conexión\nengine = create_engine(f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db_name}")\n\n# 3. Volcar todo el DataFrame a PostgreSQL\ndff.to_sql(\n    name="dataset",  # Nombre que tendrá la tabla en la base de datos\n    con=engine,                 # El motor de conexión que creamos\n    if_exists="replace",        # Opciones: \'fail\' (falla si existe), \'replace\' (reemplaza la tabla), \'append\' (agrega filas)\n    index=False,                # True si quieres guardar el índice del DataFrame como una columna\n    chunksize=10000             # Recomendado para datasets grandes: inserta en bloques de 10,000 filas\n)\n\nprint("¡DataFrame exportado exitosamente a PostgreSQL!")'

In [90]:
# Sumar solo las regiones del año 1945
suma_regiones_1945 = df_regional[df_regional['year'] == 1945][['christianity_protestant', 'christianity_romancatholic']].sum()
print("Suma de regiones 1945:\n", suma_regiones_1945)

print("\nValor en df_global para 1945:")
print(df_global[df_global['year'] == 1945][['christianity_protestant', 'christianity_romancatholic']])

Suma de regiones 1945:
 christianity_protestant       160887585
christianity_romancatholic    391332035
dtype: int64

Valor en df_global para 1945:
   christianity_protestant  christianity_romancatholic
0                160887585                   391332035