In [25]:
import kagglehub
import os

path = kagglehub.dataset_download(
    "umichigan/world-religions"
)

print("Ruta:", path)

files = os.listdir(path)
print(f'\n"Archivos:", {files}')

Ruta: C:\Users\Coder\.cache\kagglehub\datasets\umichigan\world-religions\versions\1

"Archivos:", ['global.csv', 'national.csv', 'regional.csv']

In [26]:
import pandas as pd

df_global = pd.read_csv(os.path.join(path, "global.csv"))

df_regional = pd.read_csv(os.path.join(path, "regional.csv"))

df_national = pd.read_csv(os.path.join(path, "national.csv"))

In [27]:
df_global.head()

,year,christianity_protestant,christianity_romancatholic,christianity_easternorthodox,christianity_anglican,christianity_other,christianity_all,judaism_orthodox,judaism_conservative,judaism_reform,...,baha’i_percent,taoism_percent,jainism_percent,confucianism_percent,syncretism_percent,animism_percent,noreligion_percent,otherreligion_percent,religion_sumpercent,total_percent
0,1945,160887585,391332035,98501171,36955033,13674466,701350290,856827,1426350,1929388,...,0.0000,0.0001,0.0000,0.0000,0.2666,0.0207,0.0955,0.0061,1.012061,0.718667
1,1950,133301043,401935856,106610911,38307544,16324768,696480122,2204231,1860297,2528641,...,0.0003,0.0004,0.0008,0.0012,0.1945,0.0400,0.0869,0.0055,1.011166,0.802432
2,1955,189347338,474378130,111661338,38177572,22437724,836002102,2496432,1653007,2225241,...,0.0003,0.0005,0.0006,0.0012,0.1521,0.0370,0.1199,0.0084,1.011792,0.834366
3,1960,220293770,541957872,118268109,41846700,44601144,966967595,2818847,1716903,2300405,...,0.0004,0.0005,0.0007,0.0012,0.1113,0.0465,0.1488,0.0065,1.013598,0.873137
4,1965,234437703,614115021,125954494,45086639,55119929,1074713786,3295632,1760345,2348076,...,0.0005,0.0005,0.0007,0.0014,0.1094,0.0491,0.1446,0.0126,1.006728,0.884908

In [28]:
df_regional.head()

# df_regional['region'].unique()

,year,region,christianity_protestant,christianity_romancatholic,christianity_easternorthodox,christianity_anglican,christianity_other,christianity_all,judaism_orthodox,judaism_conservative,...,taoism_percent,jainism_percent,confucianism_percent,syncretism_percent,animism_percent,noreligion_percent,otherreligion_percent,religion_sumpercent,total_percent,worldpopulation_percent
0,1945,Africa,2074180,672337,7251492,419457,4170594,14588060,0,0,...,0.0000,0.0,0.0,0.0000,0.3151,0.0003,0.0014,0.9997,1.0000,0.0180
1,1945,Asia,2407144,2222908,181928,3142204,1964907,9919091,0,0,...,0.0002,0.0,0.0,0.6378,0.0340,0.0462,0.0002,1.0043,1.0505,0.4103
2,1945,Europe,83145512,216041422,86503645,29855595,5361826,420908000,0,0,...,0.0000,0.0,0.0,0.0000,0.0023,0.1780,0.0045,0.8220,1.0000,0.3468
3,1945,Mideast,87174,635929,3180260,0,108332,4011695,0,0,...,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0073,1.0000,1.0000,0.0403
4,1945,West. Hem,73173575,171759439,1383846,3537777,2068807,251923444,856827,1426350,...,0.0000,0.0,0.0,0.0190,0.0008,0.0795,0.0230,0.9377,1.0172,0.1790

In [29]:
df_national.head()

# df_national['state'].unique()

,year,state,code,christianity_protestant,christianity_romancatholic,christianity_easternorthodox,christianity_anglican,christianity_other,christianity_all,judaism_orthodox,...,jainism_percent,confucianism_percent,syncretism_percent,animism_percent,noreligion_percent,otherreligion_percent,religion_sumpercent,total_percent,dual_religion,source_code
0,1945,United States of America,USA,66069671,38716742,1121898,2400000,1956807,110265118,821489,...,0.0,0.0,0.0,0.0,0.1635,0.0039,0.9961,1.0000,0,13
1,1950,United States of America,USA,73090083,42635882,3045420,3045420,1177214,122994019,1078078,...,0.0,0.0,0.0,0.0,0.1482,0.0041,0.9959,1.0000,0,18
2,1955,United States of America,USA,79294628,46402368,3454916,2572767,2277091,134001770,944000,...,0.0,0.0,0.0,0.0,0.1404,0.0193,0.9807,0.9999,0,15
3,1960,United States of America,USA,90692928,50587880,3334535,2710065,2908939,150234347,973500,...,0.0,0.0,0.0,0.0,0.1193,0.0076,0.9924,0.9999,0,13
4,1965,United States of America,USA,94165803,64761783,4792868,2822149,973155,167515758,991200,...,0.0,0.0,0.0,0.0,0.1020,0.0030,0.9970,1.0001,0,20

In [30]:
# Sumar solo las regiones del año 1945
suma_regiones_1945 = df_national[df_national['year'] == 1945][['christianity_all']].sum()
print("Suma de naciones 1945:\n", suma_regiones_1945)

print("\nValor en df_global para 1945:")
print(df_global[df_global['year'] == 1945][['christianity_all']])

Suma de naciones 1945:
 christianity_all    701350290
dtype: int64

Valor en df_global para 1945:
   christianity_all
0         701350290

In [31]:
'''from sqlalchemy import create_engine

import os
from dotenv import load_dotenv  

load_dotenv()

# 1. Configura los datos de conexión a tu base de datos PostgreSQL
# Estructura: postgresql+psycopg2://usuario:contraseña@host:puerto/nombre_base_datos
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")
db_name = os.getenv("DB_NAME")

# 2. Crear el motor (engine) de conexión
engine = create_engine(f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db_name}")

# 3. Iterar, filtrar y enviar cada tabla a PostgreSQL de forma automática
for name, cols in religion_groups.items():
  table_name = f'global_{name}'
  df_global_indexed[cols].to_sql(
      table_name, engine, if_exists='replace', index=False
  )
  print(f'Table created/updated in Postgres: {table_name}')


print("¡DataFrame successfully exported to PostgreSQL!")'''

'from sqlalchemy import create_engine\n\nimport os\nfrom dotenv import load_dotenv  \n\nload_dotenv()\n\n# 1. Configura los datos de conexión a tu base de datos PostgreSQL\n# Estructura: postgresql+psycopg2://usuario:contraseña@host:puerto/nombre_base_datos\nuser = os.getenv("DB_USER")\npassword = os.getenv("DB_PASSWORD")\nhost = os.getenv("DB_HOST")\nport = os.getenv("DB_PORT")\ndb_name = os.getenv("DB_NAME")\n\n# 2. Crear el motor (engine) de conexión\nengine = create_engine(f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{db_name}")\n\n# 3. Iterar, filtrar y enviar cada tabla a PostgreSQL de forma automática\nfor name, cols in religion_groups.items():\n  table_name = f\'global_{name}\'\n  df_global_indexed[cols].to_sql(\n      table_name, engine, if_exists=\'replace\', index=False\n  )\n  print(f\'Table created/updated in Postgres: {table_name}\')\n\n\nprint("¡DataFrame successfully exported to PostgreSQL!")'